name: 'alshdavid/action-ssh-runner'
description: 'Run SSH commands on SSH remote'
inputs:
  ssh-private-key:
    description: 'Private SSH key to register in the SSH agent'
    required: true
  run:
    description: 'Script to run'
    required: true
  shell:
    description: 'Shell to use'
    default: 'bash'
    required: false
  host:
    description: 'URL of ssh server'
    required: true
  user:
    description: 'User name'
    required: true
  port:
    description: 'Server port'
    required: true
    default: '22'

runs:
  using: 'composite'
  steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: "${{ inputs.ssh-private-key }}"
    - shell: bash
      env:
        SHELL: ${{ inputs.shell }}
        RUN: ${{ inputs.run }}
        HOST: ${{ inputs.host }}
        USER: ${{ inputs.user }}
        PORT: ${{ inputs.port }}
      run: |
        if [ "${SHELL}" = "bash" ]; then
          CMD="source \$HOME/.bashrc;\nset -ev;\n${RUN}"
          CMD="echo \"${CMD}\" | bash -"
        fi

        if [ "${SHELL}" = "zsh" ]; then
          CMD="source \$HOME/.zshrc;\nset -ev;\n${RUN}"
          CMD="echo \"${CMD}\" | zsh -"
        fi

        if [ "$CMD" = "" ]; then
          echo Invalid shell selected
          exit 1
        fi

        ssh -q -o StrictHostKeyChecking=no -p $PORT $USER@$HOST "$CMD"
